name: Genera animazione

on:
  # Esegui automaticamente ogni 24 ore
  schedule:
    - cron: "0 */24 * * *"
  
  # Consente di eseguire manualmente il job in qualsiasi momento
  workflow_dispatch:
  
  # Esegui su ogni push sul branch master
  push:
    branches:
      - master
    
jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Genera il gioco "snake" dalla griglia delle contribuzioni di un utente GitHub (<github_user_name>), producendo un'animazione SVG in <svg_out_path>
      - name: Genera github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
          
      # Pusha il contenuto di <build_dir> su un branch
      # Il contenuto sarà disponibile su https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, o come pagina GitHub
      - name: Pusha github-contribution-grid-snake.svg sul branch di output
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
